#Server Configuration
server:
  port: 6969

#App Configuration
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: LOGIN-SERVICE
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login/**
          filters:
            - name: CircuitBreaker
              args:
                name: LOGIN-SERVICE
                fallbackuri: forward:/login-service-fallback
        - id: TOKEN-SERVICE
          uri: lb://TOKEN-SERVICE
          predicates:
            - Path=/token/**
          filters:
            - name: CircuitBreaker
              args:
                name: TOKEN-SERVICE
                fallbackuri: forward:/token-service-fallback

#Circuit Breaker
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          timeoutInMilliseconds: 5000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost