server:
  port: 3001

spring:
  application:
    name: login-service

zipkin:
  base-url: http://0.0.0.0:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost